# Generated by Django 4.1.1 on 2022-12-17 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_profile_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='days_work',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='minutes',
        ),
    ]
