# Generated by Django 4.1.1 on 2022-12-17 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_author_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='author',
        ),
    ]
