# Generated by Django 4.1.1 on 2022-12-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_hours_end_alter_hours_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hours',
            name='end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='hours',
            name='start',
            field=models.TimeField(),
        ),
    ]
