# Generated by Django 4.1.1 on 2022-12-22 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_hours_end_alter_hours_start_startwork_endwork'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startwork',
            name='worker',
        ),
        migrations.DeleteModel(
            name='EndWork',
        ),
        migrations.DeleteModel(
            name='StartWork',
        ),
    ]
